heat_template_version: 2014-10-16

description: >
  This heat template creates a loadbalancer/listener/pool/members/healthmonitor from already existing tenant resoruces.  It is intended to be a simpler example than my_tenant_lbaas_scaleup.yaml.

parameters: 
  public_network: 
    type: string
    default: external
    description: name of the external network
  lb_subnet:
    type: string
    description: id of subnet to loadbalance
    default: 95f686f6-1cfe-4cb9-bf17-458999c5b1c6
  lb_port:
    type: number
    description: port lb listens on
    default: 80
  lb_app_port:
    type: number
    default: port for application
    default: 80
  member1_ip:
    type: comma_delimited_list
    default: 192.168.123.6,192.168.123.4
 
resources:
  load-balancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties: 
      description: lbaasv2 loadbalancer
      name: lbaas_demo_loadbalancer
      vip_subnet: { get_param: lb_subnet }

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: load-balancer }
      protocol: HTTP
      protocol_port: { get_param: lb_port }

  pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: { get_resource: listener }
      members: { get_param: member1_ip }

  pool_member1:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_param: member1_ip }
      protocol_port: { get_param: lb_app_port }
      subnet: { get_param: lb_subnet }

  monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      delay: 30
      type: HTTP
      timeout: 5
      max_retries: 10
      pool: { get_resource: pool }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_attr: [load-balancer, vip_port_id ]}

outputs: 
  loadbalancer_id: 
    value: { get_resource: load-balancer }
    description: "id the loadbalancer"
  pool_id: { get_resource: pool }
    descriptpion: "id of pool" 
